[project]
name = "open-claude-cowork"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "e2b-code-interpreter==2.0.0",
    "fastmcp==2.12.4",
]
